#!/bin/bash

# Enhanced ASCII scorecard generator with detailed innings
echo "=================================================="
echo "              Cricket Match Scorecard              "
echo "--------------------------------------------------"
echo "Pakistan vs India"
echo "--------------------------------------------------"

# First Innings
echo "1st INNINGS (Pakistan: 185/4 in 15.2 overs)"
echo "--------------------------------------------------"
echo "BATTING:"
echo "Batter           R    B   4s  6s  SR"
echo "--------------------------------------------------"
echo "Babar Azam*      82   48   8   3   170.83"
echo "M Rizwan         45   28   4   2   160.71"
echo "Iftikhar Ahmed   35   15   2   4   233.33"
echo "Shadab Khan      18   12   1   1   150.00"
echo "M Nawaz          5    4    0   0   125.00"
echo "--------------------------------------------------"
echo "Extras (b 0, lb 2, w 4, nb 1)                   7"
echo "TOTAL                                    185/4 (15.2)"
echo "Did not bat: Haider Ali, Asif Ali, Naseem Shah"
echo "--------------------------------------------------"
echo "Fall of wickets: 1-45 (Rizwan), 2-102 (Iftikhar),"
echo "3-150 (Shadab), 4-180 (Nawaz)"
echo "--------------------------------------------------"
echo "BOWLING:"
echo "Bowler           O    M    R    W   ECON"
echo "--------------------------------------------------"
echo "Shaheen Afridi   4    1    28   2   7.00"
echo "Haris Rauf       3    0    35   1   11.67"
echo "M Wasim          2    0    22   1   11.00"
echo "Shadab Khan      4    0    45   0   11.25"
echo "Naseem Shah      2.2  0    25   0   10.71"
echo "--------------------------------------------------"

# Second Innings
echo ""
echo "2nd INNINGS (India: 182/7 in 15.2 overs)"
echo "--------------------------------------------------"
echo "BATTING:"
echo "Batter           R    B   4s  6s  SR"
echo "--------------------------------------------------"
echo "KL Rahul         55   32   6   2   171.88"
echo "R Sharma         32   24   4   1   133.33"
echo "V Kohli          48   28   4   3   171.43"
echo "S Yadav         22   15   2   1   146.67"
echo "H Pandya        15   10   1   1   150.00"
echo "--------------------------------------------------"
echo "Extras (b 2, lb 4, w 3, nb 1)                   10"
echo "TOTAL                                    182/7 (15.2)"
echo "Did not bat: DK Pant, R Jadeja"
echo "--------------------------------------------------"
echo "Fall of wickets: 1-54 (Rahul), 2-98 (Sharma),"
echo "3-145 (Kohli), 4-160 (Yadav), 5-175 (Pandya)"
echo "--------------------------------------------------"
echo "BOWLING:"
echo "Bowler           O    M    R    W   ECON"
echo "--------------------------------------------------"
echo "B Kumar          4    0    42   2   10.50"
echo "A Patel          3    0    32   2   10.67"
echo "Y Chahal         4    0    45   1   11.25"
echo "H Pandya         2.2  0    35   1   15.00"
echo "R Jadeja         2    0    28   1   14.00"
echo "--------------------------------------------------"

# Match Summary
echo ""
echo "MATCH SUMMARY:"
echo "--------------------------------------------------"
echo "Pakistan won by 3 runs"
echo "Player of the Match: Babar Azam (82 off 48)"
echo "--------------------------------------------------"
echo "Current Run Rate: 12.07"
echo "Last 5 overs: 12 14 8 15 11"
echo "=================================================="